apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-rollout
spec:
  replicas: 5
  selector:
    matchLabels:
      app: jobskills
  template:
    metadata:
      labels:
        app: jobskills
    spec:
      containers:
      - name: jobskills
        image: madhumathi0406/jobskillapp:latest
        ports:
        - containerPort: 5000
  strategy:
    canary:
      steps:
      - setWeight: 25
        pause: {}
