apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-rollout   
  namespace: jobskills-ns
spec:
  template:
    metadata:
      labels:
        app: jobskills
    spec:
      containers:
      - name: jobskills
        image: madhumathi0406/jobskillapp:latest
        ports:
        - containerPort: 5000
  selector:
    matchLabels:
      app: jobskills
  replicas: 10
  strategy:
    canary:
      steps:
      - setWeight: 25
      - pause: {}


