apiVersion: v1
kind: Service
metadata:
  name: jobskills
  labels:
    app: jobskills
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30007
  selector:
    app: jobskills
